version: '3.3'

networks:
  elknet:
    driver: overlay

volumes:
  es_data_1:
  es_data_2:
  es_data_3:
  caddy_data:

services:

  node-01:
    image: elasticsearch:6.5.4
    networks:
      - elknet
    environment:
      node.name: 'node-01'
      network.publish_host: 'node-01'
      discovery.zen.ping.unicast.hosts: 'node-02,node-03'
      cluster.name: 'es-cluster'
      node.master: 'true'
      node.ingest: 'true'
      node.data: 'true'
      node.attr.zone: 'a' # shard allocation
      ES_JAVA_OPTS: '-Xms512M -Xmx512M -XX:ParallelGCThreads=1 -XX:CICompilerCount=2' # prevent ES from overallocation resources
    volumes:
      - es_data_1:/usr/share/elasticsearch/data
    configs:
      - source: es_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    stop_grace_period: '1m30s'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '512M'
      restart_policy:
        condition: 'any'
        delay: '30s'

  node-02:
    image: elasticsearch:6.5.4
    networks:
      - elknet
    environment:
      node.name: 'node-02'
      network.publish_host: 'node-02'
      discovery.zen.ping.unicast.hosts: 'node-01,node-03'
      cluster.name: 'es-cluster'
      node.master: 'true'
      node.ingest: 'true'
      node.data: 'true'
      node.attr.zone: 'b' # shard allocation
      ES_JAVA_OPTS: '-Xms512M -Xmx512M -XX:ParallelGCThreads=1 -XX:CICompilerCount=2' # prevent ES from overallocation resources
    volumes:
      - es_data_2:/usr/share/elasticsearch/data
    configs:
      - source: es_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    stop_grace_period: '1m30s'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '512M'
      restart_policy:
        condition: 'any'
        delay: '30s'

  node-03:
    image: elasticsearch:6.5.4
    networks:
      - elknet
    environment:
      node.name: 'node-03'
      network.publish_host: 'node-03'
      discovery.zen.ping.unicast.hosts: 'node-01,node-02'
      cluster.name: 'es-cluster'
      node.master: 'true'
      node.ingest: 'true'
      node.data: 'true'
      node.attr.zone: 'c' # shard allocation
      ES_JAVA_OPTS: '-Xms512M -Xmx512M -XX:ParallelGCThreads=1 -XX:CICompilerCount=2' # prevent ES from overallocation resources
    volumes:
      - es_data_3:/usr/share/elasticsearch/data
    configs:
      - source: es_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    stop_grace_period: '1m30s'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '512M'
      restart_policy:
        condition: 'any'
        delay: '30s'

  proxy:
    image: felixfischer/caddy-docker:latest
    hostname: caddy
    command: '-conf "/etc/caddy/Caddyfile" -agree=true -email ops@neulandherzer.com -log /etc/caddy/logs/caddy.log'
    expose: [80,443,9200,9300]
    ports:
      - "80:80"
      - "443:443"
      - "9200:9200"
      - "9300:9300"
    volumes:
      - caddy_data:/etc/caddy
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    environment:
      CADDYPATH: /etc/caddy
      ACME_AGREE: 'true'
    networks:
      - elknet
    deploy:
      replicas: 2
      resources:
        limits:
          memory: '128M'
        reservations:
          memory: '64M'
      restart_policy:
        condition: 'any'
        delay: '30s'

configs:
  es_config:
    file: elasticsearch.yml
  caddy_config:
    file: Caddyfile
